# This file is centrally managed
# https://github.com/domdomegg/domdomegg/blob/master/file-sync/web.yaml

name: web

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: npm ci
      - name: "Lint"
        run: npm run lint --if-present
      - name: "Build"
        run: npm run build --if-present
      - name: "Test"
        run: npm run test --if-present
      - name: "Deploy"
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build